[build]
  command = "vite build && vite build --ssr src/entry-server.tsx --outDir dist/server && node prerender.js"
  publish = "dist/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
